version: '3.8'

services:
  # Load balancer for multiple N8n instances
  nginx:
    image: nginx:alpine
    container_name: unpackai-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - n8n-1
      - n8n-2
      - n8n-3
    networks:
      - unpackai-network

  # N8n Instance 1
  n8n-1:
    image: n8nio/n8n:latest
    container_name: unpackai-n8n-1
    restart: unless-stopped
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=unpackai2024
      - N8N_HOST=n8n-1
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://n8n-1:5678/
    volumes:
      - n8n_data_1:/home/node/.n8n
    networks:
      - unpackai-network

  # N8n Instance 2
  n8n-2:
    image: n8nio/n8n:latest
    container_name: unpackai-n8n-2
    restart: unless-stopped
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=unpackai2024
      - N8N_HOST=n8n-2
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://n8n-2:5678/
    volumes:
      - n8n_data_2:/home/node/.n8n
    networks:
      - unpackai-network

  # N8n Instance 3
  n8n-3:
    image: n8nio/n8n:latest
    container_name: unpackai-n8n-3
    restart: unless-stopped
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=unpackai2024
      - N8N_HOST=n8n-3
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://n8n-3:5678/
    volumes:
      - n8n_data_3:/home/node/.n8n
    networks:
      - unpackai-network

  # Redis for job distribution
  redis:
    image: redis:7-alpine
    container_name: unpackai-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - unpackai-network

volumes:
  n8n_data_1:
  n8n_data_2:
  n8n_data_3:
  redis_data:

networks:
  unpackai-network:
    driver: bridge
